version: "3.9"

services:

  # ----------------------------
  # MONGO
  # ----------------------------
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # ----------------------------
  # ZOOKEEPER
  # ----------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # ----------------------------
  # KAFKA
  # ----------------------------
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"

  # ----------------------------
  # GATEWAY
  # ----------------------------
  gateway:
    build: ./backend/gateway
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
      - product-service

  # ----------------------------
  # AUTH SERVICE
  # ----------------------------
  auth-service:
    build: ./backend/auth-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka

  # ----------------------------
  # PRODUCT SERVICE
  # ----------------------------
  product-service:
    build: ./backend/product-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/products
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka

  # ----------------------------
  # CART SERVICE
  # ----------------------------
  cart-service:
    build: ./backend/cart-service
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/cart
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka

  # ----------------------------
  # ORDER SERVICE
  # ----------------------------
  order-service:
    build: ./backend/order-service
    ports:
      - "5004:5004"
    environment:
      - MONGO_URI=mongodb://mongo:27017/orders
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka

  # ----------------------------
  # WALLET SERVICE
  # ----------------------------
  wallet-service:
    build: ./backend/wallet-service
    ports:
      - "5005:5005"
    environment:
      - MONGO_URI=mongodb://mongo:27017/wallet
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka

  # ----------------------------
  # FRONTEND
  # ----------------------------
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - gateway

volumes:
  mongo_data: